name: nqnhan_rubik
description: "A new Flutter project."
publish_to: 'none' # XÃ³a dÃ²ng nÃ y náº¿u sau nÃ y muá»‘n publish lÃªn pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI cÆ¡ báº£n
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^3.0.3
  provider: ^6.1.1

  # LÆ°u trá»¯ local
  shared_preferences: ^2.2.3

  # Thá»i gian / format
  intl: ^0.18.1
  timeago: ^3.6.1

  # AI / toÃ¡n há»c / xá»­ lÃ½ luá»“ng
  collection: ^1.18.0      # tiá»‡n cho thuáº­t toÃ¡n AI, xá»­ lÃ½ list/map nÃ¢ng cao
  rxdart: ^0.27.7          # stream nÃ¢ng cao (AI async, hint tá»«ng bÆ°á»›c Rubik)
  vector_math: ^2.1.4      # toÃ¡n vector, ma tráº­n xoay Rubik

  # Hiá»‡u á»©ng UI / animation cho game
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  confetti: ^0.7.0         # mÆ°a phÃ¡o giáº¥y khi ngÆ°á»i chÆ¡i solve thÃ nh cÃ´ng ğŸ˜

  # Auth / backend / config
  jwt_decoder: ^2.0.1      # Ä‘á»c JWT Ä‘á»ƒ láº¥y userId, role...
  http: ^1.5.0             # call API .NET Core
  flutter_dotenv: ^6.0.0   # load BASE_URL tá»« file .env

  # Camera scanning Rubik
  camera: ^0.11.2+1
  permission_handler: ^12.0.1
  image: ^4.5.4            # xá»­ lÃ½ pixel, Ä‘á»c mÃ u tá»«ng Ã´ Rubik tá»« frame camera

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0     # dÃ¹ng báº£n má»›i hÆ¡n

flutter:
  uses-material-design: true

  assets:
    - .env
    - images/
